config/routes.rb
Juanjosecanocortes::Application.routes.draw do
  
  # get "prediciendo" => "home#prediciendo", :as => "prediciendo"
  # get "metirium" => "home#metirium", :as => "metirium"
  # get "thealarmfactory" => "home#thealarmfactory", :as => "thealarmfactory"
  get "finderforperiscope" => "home#finderforperiscope", :as => "finderforperiscope"
  # get "turismovital" => "home#turismovital", :as => "turismovital"
  
  get "cem" => "home#cem", :as => "cem"
  get "eventoxperienzia" => "home#eventoxperienzia", :as => "eventoxperienzia"
  get "quiz" => "home#quiz", :as => "quiz"
  
  resources :home, :only => [:index]
  resources :contacts, :only => [:index, :create]
  
  root :to => 'home#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone, :captcha_response
  attr_accessor :captcha_response
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  layout false
  
  def index
    authenticate
    @contacts = Contact.order("created_at desc")
  end
  
  def create 
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if verify_recaptcha(model: @contact, response: params["contact"]["captcha_response"]) && @contact.save
        render :json => @contact.as_json, :status => 200 and return
      else
        render :json => nil, :status => 500 and return
      end
    end
  end
  
  protected
  
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == Juanjosecanocortes::Application.config.http_authentication_user && password == Juanjosecanocortes::Application.config.http_authentication_password
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @contact = Contact.new
  end
  
  def prediciendo
  end
  
  def metirium
  end
  
  def thealarmfactory
  end
  
  def finderforperiscope
  end
  
  def turismovital
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/index.html.erb
<div class="container">
  <% @contacts.each do |contact| %>
    <div class="row">
      <p><%= contact.created_at %></p>
      <p><%= contact.name %></p>
      <p><%= contact.email %></p>
      <p><%= contact.phone %></p>
      <p><%= contact.message %></p>
      <hr>
    </div>
  <% end %>
</div>

app/views/home/_services.html.erb

<!-- Services Section -->
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Services</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">E-Commerce</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Responsive Design</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Web Security</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
        </div>
    </div>
</section>

app/views/home/cem.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://empirica5.com">Customer Experience Manager</a></h2>
            <p class="item-intro text-muted">Plataforma que permite realizar el seguimiento de la satisfacción de los clientes.</p>
            <%= image_tag "portfolio/cem1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/cem2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/cem3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/cem4.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/eventoxperienzia.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://app.eventoxperienzia.com/foropyme/vi-foro-pyme-bilbao?section=home">Eventoxperienzia.com</a></h2>
            <p class="item-intro text-muted">Aplicación para la creación automatizada de webapps para eventos.</p>
            <%= image_tag "portfolio/evento1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/evento2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/evento3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/app1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/app2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/app3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/finderforperiscope.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="https://play.google.com/store/apps/details?id=games.freakapps.periscopersclub">Finder for Periscope</a></h2>
            <p class="item-intro text-muted">App móvil que permite realizar búsquedas por palabras en la red social Periscope.</p>
            <%= image_tag "portfolio/periscope1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/periscope2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/periscope3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/periscope4.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/index.html.erb
<!-- Header -->
<header>
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Freelance tecnológico.<br>Full stack developer en Ruby on Rails.</div>
            <a href="#about" class="page-scroll btn btn-xl">Lo que hago</a>
            <%= link_to "Contacta", "#contact", :class => "page-scroll btn btn-xl" %>
        </div>
    </div>
</header>

<!-- About Section -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3 class="section-subheading text-muted curriculum">Soy Juan José Cano-Cortés Cartagena. Nacido en 1971, llevo desde los 15 años utilizando 
                ordenadores para jugar, trabajar y experimentar.<br>
                He trabajado durante 17 años en empresas tecnológicamente punteras en sectores como la cartografía digital y el marketing.<br>
                He creado un par de empresas de desarrollo de software propio y para terceros.<br>
                Y he ganado dos hackatones.<br>
                Puedes ver <a href="http://bit.ly/1P6ofG6">mi perfil completo en LinkedIn</a>.<br><br>
                Ahora, utilizo mis conocimientos y experiencia como freelance de desarrollo y de consultoría, abarcando un amplio rango de tecnologías.</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <ul class="timeline">
                    <li>
                        <div class="timeline-image">
                            <%= image_tag "about/code.png", :class => "img-circle img-responsive", :alt => "" %>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>DESARROLLO WEB</h4>
                                <h4 class="subheading">Landing pages, productos mínimos viables, prototipos, webs corporativas</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">HTML, CSS, jQuery, Bootstrap, responsive design, Wordpress</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <%= image_tag "about/backend.jpg", :class => "img-circle img-responsive", :alt => "" %>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>DESARROLLO BACK-END</h4>
                                <h4 class="subheading">APIs, bases de datos, big data</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">SQL Server, PostgreSQL, MySQL, MVC, Ruby on Rails, C#, Solr, Elasticsearch, Redis, Social APIs</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image">
                            <%= image_tag "about/mobile.png", :class => "img-circle img-responsive", :alt => "" %>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>APLICACIONES MÓVILES</h4>
                                <h4 class="subheading">Apps corporativas, juegos, utilidades</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">iOS, Android, Java, Objective-C, Mobincube</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <%= image_tag "about/cpd.jpg", :class => "img-circle img-responsive", :alt => "" %>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Dirección técnica</h4>
                                <h4 class="subheading">Arquitecturas de software, escalabilidad, servicios cloud</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">AWS, Heroku, microservicios, APIs</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-image">
                        <div class="timeline-image">
                            <%= image_tag "about/marketing.png", :class => "img-circle img-responsive", :alt => "" %>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>Marketing online</h4>
                                <h4 class="subheading">Analítica web, SEO, ASO, Community manager</h4>
                            </div>
                            <div class="timeline-body">
                                <p class="text-muted">Google Analytics, AdMob, AdSense, AdWords</p>
                            </div>
                        </div>
                    </li>                    
                </ul>                
            </div>              
        </div>
        <div class="row">
            <div class="col-lg-12 btn-message text-center">
              <%= link_to "Contacta", "#contact", :class => "page-scroll btn btn-xl" %>
            </div>
        <div>
    </div>
</section>

<!-- Portfolio Grid Section -->
<section id="portfolio" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Trabajos</h2>
                <h3 class="section-subheading text-muted">Estos son algunos de los proyectos que he realizado</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6 portfolio-item">
                <a href="<%= cem_path %>" class="portfolio-link">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <span class="glyphicon glyphicon-zoom-in zoom" aria-hidden="true"></span>
                        </div>
                    </div>
                    <%= image_tag "portfolio/cem1.png", :class => "img-responsive", :alt => "" %>
                </a>
                <div class="portfolio-caption">
                    <h4>Customer Experience Manager</h4>
                    <p class="text-muted">Plataforma para el seguimiento de la satisfacción de los clientes.</p>
                </div>
            </div> 

            <div class="col-md-6 col-sm-6 portfolio-item">
                <a href="<%= eventoxperienzia_path %>" class="portfolio-link">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <span class="glyphicon glyphicon-zoom-in zoom" aria-hidden="true"></span>
                        </div>
                    </div>
                    <%= image_tag "portfolio/evento1.png", :class => "img-responsive", :alt => "" %>
                </a>
                <div class="portfolio-caption">
                    <h4>Eventoxperienzia</h4>
                    <p class="text-muted">Aplicación para la creación automatizada de webapps para eventos.</p>
                </div>
            </div>
                        
        </div>
        <div class="row">
            
            <div class="col-md-6 col-sm-6 portfolio-item">
                <a href="<%= quiz_path %>" class="portfolio-link">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <span class="glyphicon glyphicon-zoom-in zoom" aria-hidden="true"></span>
                        </div>
                    </div>
                    <%= image_tag "portfolio/apps.png", :class => "img-responsive", :alt => "" %>
                </a>
                <div class="portfolio-caption">
                    <h4>Quiz Creator</h4>
                    <p class="text-muted">Constructor de apps de adivinación de canciones.</p>
                </div>
            </div>
            
            <div class="col-md-6 col-sm-6 portfolio-item">
                <a href="<%= finderforperiscope_path %>" class="portfolio-link">
                    <div class="portfolio-hover">
                        <div class="portfolio-hover-content">
                            <span class="glyphicon glyphicon-zoom-in zoom" aria-hidden="true"></span>
                        </div>
                    </div>
                    <%= image_tag "portfolio/periscope3.png", :class => "img-responsive", :alt => "" %>                    
                </a>
                <div class="portfolio-caption">
                    <h4>Finder for Periscope</h4>
                    <p class="text-muted">App móvil que permite realizar búsquedas por palabras en la red social Periscope.</p>
                </div>
            </div>
                        
        </div>
        <div class="row">
            <div class="col-lg-12 btn-message text-center">
              <%= link_to "Contacta", "#contact", :class => "page-scroll btn btn-xl" %>
            </div>
        <div>
    </div>
</section>


<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Contacta conmigo</h2>
                <h3 class="section-subheading contact-font">Explica lo más detalladamente posible cual es tu necesidad o deja tu teléfono o tu correo y me pondré en contacto contigo lo antes posible.</h3>
                <h3 class="section-subheading contact-font">También puedes escribirme directamente a jjcanocortes@gmail.com</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <%= form_for @contact do |f| %>
                    <%= f.hidden_field :captcha_response %>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.text_field :name, :class => "form-control", :placeholder => "Tu nombre *", :required => true, :data => { :'validation-required-message' => "Por favor, introduce tu nombre."} %>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :email, :class => "form-control", :placeholder => "Tu correo *", :required => true, :data => { :'validation-required-message' => "Por favor, introduce tu dirección de correo."} %>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :phone, :class => "form-control", :placeholder => "Tu teléfono *", :required => true, :data => { :'validation-required-message' => "Por favor, introduce tu teléfono."} %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.text_area :message, :class => "form-control", :placeholder => "Tu mensaje *", :required => true, :data => { :'validation-required-message' => "Por favor, introduce tu mensaje."} %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-lg-12 text-center">
                          <%= recaptcha_tags(script: false) %>
                        </div>
                        <div class="col-lg-12 text-center">
                            <div id="success"></div>
                            <button type="submit" class="btn btn-xl" id="submit-button">Enviar mensaje</button>
                        </div>
                    </div>
                    
                <% end %>
            </div>
        </div>
    </div>
</section>


<!-- Plugin JavaScript -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<%= javascript_include_tag "classie" %>
<%= javascript_include_tag "cbpAnimatedHeader.min" %>

<!-- Contact Form JavaScript -->
<%= javascript_include_tag "jqBootstrapValidation" %>
<%= javascript_include_tag "contact_me" %>

<%= javascript_tag do %>
  
  $(document).ready(function(){

    $("#submit-button").on("click", function(){
      $("#contact_captcha_response").val($("#g-recaptcha-response").val());
    });
    
  });
  
<% end %>

app/views/home/metirium.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://metirium.com">metirium.com</a></h2>
            <p class="item-intro text-muted">Aplicación por suscripción que permite registrar, analizar y representar muestras de datos procedentes de cualquier fuente.</p>
            <%= image_tag "portfolio/metirium1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/metirium2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/metirium3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/metirium4.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>

    
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/metirium5.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/prediciendo.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://prediciendo.com">prediciendo.com</a></h2>
            <p class="item-intro text-muted">Web que permite descubrir si las predicciones que realizan las instituciones se cumplen o no.</p>
            <%= image_tag "portfolio/prediciendo1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/prediciendo2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/prediciendo3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/quiz.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://empirica5.com">Quiz creator</a></h2>
            <p class="item-intro text-muted">Aplicación para la creación automática de apps de adivinación de canciones.</p>
            <%= image_tag "portfolio/apps.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/quiz.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>

app/views/home/thealarmfactory.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <h2><a href="http://thealarmfactory.com">thealarmfactory.com</a></h2>
            <p class="item-intro text-muted">Aplicación por suscripción que envía alertas a los usuarios cuando se produce una condición matemática predefinida en una muestra de datos.</p>
            <%= image_tag "portfolio/thealarmfactory1.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/thealarmfactory2.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/thealarmfactory3.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <%= image_tag "portfolio/thealarmfactory4.png", :class => "img-responsive img-centered", :alt => "" %>            
          </center>
        </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="modal-body"> 
          <center>
            <a href="<%= root_path(:anchor => "portfolio") %>" type="button" class="btn btn-primary"><i class="fa fa-times"></i> Volver a la página principal</a>
          </center>
        </div>
    </div>
  </div>
  
</div>